version: "3.7"
service:

  app:
    build: .
    container_name:
    depends_on: 
      - postgres
    ports:
      - 3000:3000
      - 9229:9229
    env_file: 
      - .env

  postgres:
    container_name:
    image: postgres:12-alpine
    hostname: ${DB_HOST}
    environment:
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}